### ISSUE TITLE
Conflicting declaration of inet_ntop with mingw-w64-9.0

### ISSUE THREAD

**Issue by manisandro** [uriparser/uriparser#117]
On Fedora we moved to mingw-w64-9.0, and uriparser fails to compile with a conflicting declaration of inet_ntop [1]. I'd suggest just dropping the extra declaration:

    diff -rupN uriparser-0.9.5/tool/uriparse.c uriparser-0.9.5-new/tool/uriparse.c
    --- uriparser-0.9.5/tool/uriparse.c     2021-03-18 17:35:29.000000000 +0100
    +++ uriparser-0.9.5-new/tool/uriparse.c 2021-07-23 10:48:26.655075428 +0200
    @@ -43,10 +43,6 @@
    #ifdef _WIN32
    # include <winsock2.h>
    # include <ws2tcpip.h>
    -# ifdef __MINGW32__
    -WINSOCK_API_LINKAGE const char WSAAPI inet_ntop(
    -               int af, const void *src, char *dst, socklen_t size);
    -# endif
    #else
    # include <sys/socket.h>
    # include <arpa/inet.h>

[1] https://kojipkgs.fedoraproject.org//work/tasks/2526/72422526/build.log

**Comment by hartwork** [comment]
Hi @manisandro ,

I'm unsure which versions of MinGW we'll break with dropping the line and if that's okay. A version guard could help mitigate, so I guess in all cases more research first would help estimate potential consequences. I should probably add MinGW coverage to the CI in here first, in any case.

PS: related commits are:
- b8be1b97d0a3f239c60dd236a6493987c45e0403
- 8bdd07e21b55f72b9c9650d197d40c7b41d8553d

**Comment by hartwork** [comment]
PS: @manisandro thanks for taking this upstream! :pray:

**Comment by hartwork** [comment]
@manisandro should be fixed by f04d0eedc6028822a393ede583e071df54832b5e, the new GCC 9 MinGW CI likes it.
