### ISSUE TITLE
Possible incorrect output from `uriUriStringToUnixFilenameA()`

### ISSUE THREAD

**Issue by vs49688** [uriparser/uriparser#12]
I have a Java program that makes some URIs and sends them to a C++ program (using uriparser) to something with. Below is an example of what Java's giving me:

```bash
ubuntu@DEV:~$ jshell
|  Welcome to JShell -- Version 10.0.1
|  For an introduction type: /help intro

jshell> Path p = Paths.get("/home/ubuntu/")
p ==> /home/ubuntu

jshell> p.toUri()
$2 ==> file:///home/ubuntu/

jshell> p.resolve("somefolder/").toUri()
$3 ==> file:///home/ubuntu/somefolder/

jshell> p.toUri().resolve("somefolder/")
$4 ==> file:/home/ubuntu/somefolder/
```

I'm running under the assumption that Java is doing the right thing here. Putting those URIs into `uriparse`:

```bash
ubuntu@DEV:~/Desktop/urib/build$ ./uriparse file:///home/ubuntu/somefolder/
uri:          file:///home/ubuntu/somefolder/
scheme:       file
hostText:     
 .. pathSeg:  home
 .. pathSeg:  ubuntu
 .. pathSeg:  somefolder
 .. pathSeg:  
absolutePath: false
              (always false for URIs with host)
```

```bash
ubuntu@DEV:~/Desktop/urib/build$ ./uriparse file:/home/ubuntu/somefolder/
uri:          file:/home/ubuntu/somefolder/
scheme:       file
 .. pathSeg:  home
 .. pathSeg:  ubuntu
 .. pathSeg:  somefolder
 .. pathSeg:  
absolutePath: true
```

Now, for the actual issue:

If I stick those URIs into `uriUriStringToUnixFilenameA()`, I get:
  * `file:///home/ubuntu/somefolder/` -> `/home/ubuntu/somefolder/`, and
  * `file:/home/ubuntu/somefolder/` -> `file:/home/ubuntu/somefolder/`

My other code chockes on the second output as it's expecting a valid path.

Does this look like a bug in uriparser, or am I simply using it wrong?

I've attached a sample program [here](https://gist.github.com/vs49688/583f1f6d7824493f75beedfae7dfdbc3) that shows this behaviour.

If this is indeed a bug I have a patch ready, but I'd want to be sure first.

EDIT: This is using current master (20ae776ab86bf776c97086064a1f6a78bffcabfd)

**Comment by hartwork** [comment]
I checked https://tools.ietf.org/html/rfc8089#appendix-B now: It looks like `file:/home/ubuntu/somefolder/` should be supported. I'm looking forward to your pull request.
