### ISSUE TITLE
URI manipulation advice

### ISSUE THREAD

**Issue by raj-blis** [uriparser/uriparser#167]
Hello, 

Is it possible to do URL manipulation using the uriparser library - e.g. removing fragments OR removing certain query parameters? 

Any advice would be much useful. 

Thanks!

**Comment by hartwork** [comment]
Hi @raj-blis, definitely possible, yes. I would recommend to:
- check https://uriparser.github.io/doc/api/latest/structUriUriStructA.html
- use LeakSanitizer/AddressSanitizer to be sure that your modifications are free of memory leaks and bad memory access

**Comment by hartwork** [comment]
@raj-blis all you need is linked lists, malloc, free, re-writing pointers, plain C. In some sense uriparser leaves the "easy but annoying" bit to you compared to things like parsing and URI resolution. I can offer we jump on a ~30 minutes Jitsi call (https://meet.jit.si/) if you get stuck, but that's all I can offer here at the moment.
