### ISSUE TITLE
Migrate to CMake / Overly complicated Windows building

### ISSUE THREAD

**Issue by computerquip-streamlabs** [uriparser/uriparser#17]
I'd like to use this in my own project but getting this running on Windows hasn't proven obvious and there are no instructions (outside of the possibility of just adding all the source files and include files into my own project which might be intended) .

Is there any chance I could convince you to adopt a CMake/Meson/\<literally anything else other than autotools\> for a build system?

**Comment by hartwork** [comment]
Pesonally I "like" GNU Autotools and never really "liked" CMake but I get that CMake does a lot more for us with targetting non-Unix systems so it's only a matter of time until Autotools alone (or at all) stops sufficing.

**Comment by hartwork** [comment]
Fixed by merge of #47

For any potential issues with the CMake integration, please open new tickets. Thank you!
