### ISSUE TITLE
Scheme based normalization?

### ISSUE THREAD

**Issue by estobbart** [uriparser/uriparser#173]
Section 6.23. describes scheme based normalization..
https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.3

Right now, it doesn't appear to apply this normalization.
I believe the expectation is that creating a URI of `http://example.org`, would return `http://example.org/` from the ToString method.
Is that what this comment is referencing?
https://github.com/uriparser/uriparser/blob/master/src/UriRecompose.c#L423

Is this out of scope due to it referencing other RFC's?

**Comment by estobbart** [comment]
Of course. May helpful to note that in the ToString method that normalization/6.2.3 is an application responsibility. Maybe providing an optional normalization callback would help signal the intent as well.

**Comment by hartwork** [comment]
@estobbart I have created a related pull request #174 now. Would you say that's good enough?
