### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [uriparser/uriparser#24]
Hi Uriparser team,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by hartwork** [comment]
Private report to sebastian@pipping.org would be nice. Would that work for you?

**Comment by Google-Autofuzz** [comment]
Hi Sebastian,

Without knowing all the ways people are using the package, it's hard to know the line for "crazy stuff".  :)  If it is ok with you, we'll send security bugs to your address, and you are welcome to add them to the public tracker at your discretion.  It is our preference to be conservative when disclosing security bugs.  

I should also mention that after 90 days of reporting, we typically open the bug up to anyone who might want to contribute patch (and receive a [patch reward](https://www.google.com/about/appsecurity/patch-rewards/autofuzz/)).  This will be mentioned in our future reports, but it's worth mentioning here too:  you're eligible for [OSS-Fuzz integration](https://github.com/google/oss-fuzz), which streamlines this process significantly.  There are also [integration rewards available](https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html).

Thank you so much for the quick response!


Matt
Autofuzz Team
