### ISSUE TITLE
Uriparser uses malloc() directly (custom allocator support)

### ISSUE THREAD

**Issue by akritid** [uriparser/uriparser#26]
Currently uriparser uses malloc() directly. For use in some high performance systems, it would help to have an optional API call to allow overriding malloc with custom memory allocator routines. For example, see json_set_alloc_funcs() in the Jansson library. These usually take the form of malloc()-like function pointers, but it would be even more useful if the hooks take an additional void * context argument, since a custom allocator often needs access to the heap object to use.

The set_alloc_funcs() API could either take hold globally, or even better be applied on a parser state, for finer control.

**Comment by hartwork** [comment]
Hi Periklis, I get the idea, I have seen it with libexpat. Adding support for a custom allocator will need a new API function ...Ex or ...ExEx for every current API function that calls malloc/realloc/free right now to be consistent and backwards compatible, and also test coverage. If there is interest in funding development of that feature, please get in touch offline.
