### ISSUE TITLE
uriParseUriA returns URI_ERROR_SYNTAX for a valid uri?

### ISSUE THREAD

**Issue by mbulhakov** [uriparser/uriparser#34]
Hi there!

I have the following sample code:
```
UriParserStateA state; 
UriUriA uri;
state.uri = &uri;
int res = uriParseUriA(&state, R"(http://counter.yadro.ru/hit;PLUSO?q;r;s1366*768*24;uhttp%3A//masterok-kirillovka.com.ua/rooms/;h%u041E%u043F%u0438%u0441%u0430%u043D%u0438%u0435%20%u043D%u043E%u043C%u0435%u0440%u043E%u0432%20%u043D%u0430%20%u0431%u0430%u0437%u0435%20%u043E%u0442%u0434%u044B%u0445%u0430%20%u041C%u0410%u0421%u0422%u0415%u0420%u041E%u041A%20%u0432%20%u041A%u0438%u0440%u0438%u043B%u043B%u043E%u0432%u043A%u0435;1)");
uriFreeUriMembersA(&uri);
```

I used C++ for R delimiter, but you got the idea, I guess. The result of res is URI_ERROR_SYNTAX, however, url is valid and working.

Could you fix it please or say what is the reason?

Thank you!

**Comment by hartwork** [comment]
Hi Maksym,

I am not familiar with R delimiter of C++11(?) in detail. I don't see any backslashes for a motivation here, I may miss other details. Please provide C code or a raw URI, instead. Thank you!

Best, Sebastian

**Comment by mbulhakov** [comment]
Hi,

Here is a raw uri -- http://counter.yadro.ru/hit;PLUSO?q;r;s1366*768*24;uhttp%3A//masterok-kirillovka.com.ua/rooms/;h%u041E%u043F%u0438%u0441%u0430%u043D%u0438%u0435%20%u043D%u043E%u043C%u0435%u0440%u043E%u0432%20%u043D%u0430%20%u0431%u0430%u0437%u0435%20%u043E%u0442%u0434%u044B%u0445%u0430%20%u041C%u0410%u0421%u0422%u0415%u0420%u041E%u041A%20%u0432%20%u041A%u0438%u0440%u0438%u043B%u043B%u043E%u0432%u043A%u0435;1

**Comment by hartwork** [comment]
The `%u0` in there violates [RFC 3986 2.1 percent encoding](https://tools.ietf.org/html/rfc3986#section-2.1):

>  pct-encoded = "%" HEXDIG HEXDIG
