### ISSUE TITLE
IPv6 hostText Display Issue

### ISSUE THREAD

**Issue by timway** [uriparser/uriparser#42]
It's highly possible this is user error. I'm seeing the '[' being omitted from hostText but the ']' is present. The code comments seem to indicate that '[' and ']' shouldn't be in hostText but because that shows a port with the ':' separator you would seem to be required to do so. The output of a uriparse of https://[::1]:9090 and https://127.0.0.1:9090 can be seen below:

```
https://[::1]:9090
::1]:9090
::1
https://127.0.0.1:9090
127.0.0.1:9090
127.0.0.1
```

A simple and very boiled down chunk of code showing the problem:
```
#include <arpa/inet.h>
#include <uriparser/Uri.h>

int main()
{
    UriUriA u;
    const char *errorPosition;
   
    uriParseSingleUriA(&u, "https://[::1]:9090", &errorPosition);
    fprintf(stdout,"%s\n",u.scheme);
    fprintf(stdout,"%s\n",u.hostText);
    if (u.hostData.ip6)
    {   
        char ip6str[INET6_ADDRSTRLEN] = ""; 
        inet_ntop(AF_INET6, u.hostData.ip6->data, ip6str, sizeof(ip6str));
        fprintf(stdout,"%s\n",ip6str);
    }   

    uriParseSingleUriA(&u, "https://127.0.0.1:9090", &errorPosition);
    fprintf(stdout,"%s\n",u.scheme);
    fprintf(stdout,"%s\n",u.hostText);
    if (u.hostData.ip4)
    {   
        char ip4str[INET_ADDRSTRLEN] = ""; 
        inet_ntop(AF_INET, u.hostData.ip4->data, ip4str, sizeof(ip4str));
        fprintf(stdout,"%s\n",ip4str);
    }   
    return 0;
}
```

Note: I'm running uriparser from Fedora 29 repositories. It reports the version as 0.9.0-1.

**Comment by timway** [comment]
This was a misunderstanding. The structure provides essentially a start and stop value by pointers into the larger URI string. Using those start and stop values I get the expected results.

Not a bug.

**Comment by hartwork** [comment]
Excellent, thanks for the update!
