### ISSUE TITLE
Please tag for 0.9.2

### ISSUE THREAD

**Issue by jgsuess** [uriparser/uriparser#57]
Hi, I would like to use 0.9.2, because of the cmake build availability. Could you tag the repo so I can pull this in?

**Comment by hartwork** [comment]
I agree that a new release is in order. I'll need a few days more

**Comment by david-antiteum** [comment]
Does this release generate the missing cmake files when installing? I have an open case in Vcpkg (https://github.com/Microsoft/vcpkg/issues/5987). 

Thanks

**Comment by hartwork** [comment]
Hi @david-antiteum the upcoming release is the first including a [`CMakeLists.txt`](https://github.com/uriparser/uriparser/blob/master/CMakeLists.txt) file. There is no better time than checking if it does what you need then now :smiley:

**Comment by hartwork** [comment]
@david-antiteum #60 that affects compilation on Windows was just merged and might be of interest to you. Do you have plans for a test spin in the next few days? I wonder if I should wait with the release more or not. Thanks!

**Comment by david-antiteum** [comment]
I can do the test next week using master.

David

**Comment by hartwork** [comment]
@david-antiteum Cool, thanks in advance!

**Comment by david-antiteum** [comment]
Looks good to me. I have compiled the version in Windows with no issues both directly and using vcpkg's install command. cmake files are configured correctly and I can just use it with:

```
find_package(uriparser CONFIG REQUIRED)
target_link_libraries(main PRIVATE uriparser::uriparser)
```

As soon as you tag the version as 0.9.2 I will update the port file for vcpkg.

Thanks.

**Comment by hartwork** [comment]
@david-antiteum thanks for testing!

The release with all its different parts is tracked at #61.

Release archives are uploaded by now, for vcpkg this might be the URL you want:
https://github.com/uriparser/uriparser/releases/download/uriparser-0.9.2/uriparser-0.9.2.zip

**Comment by david-antiteum** [comment]
Thanks ... I have opened a PR in vcpkg with the new version.

**Comment by hartwork** [comment]
Cool, thank you!

https://github.com/Microsoft/vcpkg/pull/6178
