### ISSUE TITLE
[MinGW] Add library version suffix to dll name

### ISSUE THREAD

**Issue by manisandro** [uriparser/uriparser#63]
The autotools build used to produce dll names with a version suffix, for continuity it would be good if cmake did the same. Currently, I'm using the following downstream patch [1].

[1] https://src.fedoraproject.org/rpms/mingw-uriparser/blob/master/f/uriparser_libversion.patch

**Comment by hartwork** [comment]
Hi Sandro, thanks!

Could you check pull request #64 if the changes I put on top still work fine? Thank you!

**Comment by hartwork** [comment]
PS: I'm also wondering if we want to limit this to MinGW or not — right now it affects `WIN32` e.g. including `MSVC`.

**Comment by manisandro** [comment]
Hi Sebastian, yep still works fine, thanks!

**Comment by hartwork** [comment]
Very nice, thanks for testing!
