### ISSUE TITLE
macOS: Configure does not work on Android with NDK 16 (clang)

### ISSUE THREAD

**Issue by martinell** [uriparser/uriparser#7]
I tried to run configure for cross compiling on Android and i get the following:

> checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for armv7a-linux-android-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for armv7a-linux-android-gcc... NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
checking whether the C compiler works... no
configure: error: in `.../openFrameworks/scripts/apothecary/apothecary/build/uriparser':
configure: error: C compiler cannot create executables
See `config.log' for more details

The problem is that when checking the compiler, configure tries to pass the CFLAGS to the linker and the "--sysroot" argument is not accepted by clang when linking:

> configure:3253: checking whether the C compiler works
configure:3275: NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -nostdlib --sysroot=NDK_ROOT/sysroot -fno-short-enums .... >&5
ld: unknown option: --sysroot=NDK_ROOT/sysroot
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hartwork** [comment]
Hi! Which version of Clang are you using? The configure script of uriparser 0.8.5 was generated by autoconf 2.69 to my best knowledge, the latest release upstream. Is this the first and only project you get that error with? Also, I see traces of `openFrameworks` up there. Is this even the latest version of uriparser and can you try uriparser 0.8.5 in insolation for comparision? Thank you!

**Comment by martinell** [comment]
Hi,

I tested it with 0.8.5. Yes, I'm using openFrameworks but it's just running the build script. It basically sets up the toolchain and runs the configure script.

**Comment by hartwork** [comment]
Could it be that your `ld` is too old? My GNU ld 2.28.1 understands `--sysroot`. What tools have you created the GNU toolchain in `/usr/local/bin/` with?

**Comment by martinell** [comment]
I'm not sure how to check this. The program is being linked through a "clang" command.

I'm on a mac, btw.

**Comment by hartwork** [comment]
Maybe it's not even GNU ld then, maybe [this thing](http://www.manpages.info/macosx/ld.1.html). Could you check these commands for clues?
* `which ld`
* `/usr/local/bin/ld --version`
* `/usr/local/bin/ld --help`

To use a different linker, you could configure with `./configure LD=/other/linker/path`. Clang also has an alternative to `ld` called `lld` that you could give a try, if you have a package for that at hand. Or GNU ld, if you don't have that yet. I should mention I never touched macOS for more than a few minutes.

**Comment by hartwork** [comment]
PS: You could also try running `autoconf` if you have that. With luck it generates a new configure script that better fits your platform without `--sysroot`.

**Comment by hartwork** [comment]
My impression is that we are either dealing with a bug in GNU autoconf or with a host configuration issue. I'm closing this ticket for now, please feel free to re-open if there is need to.
