### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by JamesRead5737** [uriparser/uriparser#73]
$ cmake -DCMAKE_BUILD_TYPE=Release ..
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY) (Required
  is at least version "1.8.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindGTest.cmake:196 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:247 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/yaakov/Downloads/uriparser-0.9.3/build/CMakeFiles/CMakeOutput.log".

**Comment by hartwork** [comment]
`Could NOT find GTest` is key here: You need GoogleTest installed in a findable place unless you disable the test suite at compilation time.

**Comment by hartwork** [comment]
PS: It would be `-DURIPARSER_BUILD_TESTS=OFF`.

**Comment by hartwork** [comment]
Happy to re-open, closing due to no reply.
