### ISSUE TITLE
Inconsistent GTest minimal version

### ISSUE THREAD

**Issue by wouterbeek** [uriparser/uriparser#80]
A minor issue only:
  - `CMakeLists.txt` states that the minimum required GTest version is 1.8.0.
  - `README.md` states that the minimum required GTest version is 1.8.1.

It would be nice to make these claims consistent.

**Comment by hartwork** [comment]
Back in sync now. It went out of sync related to https://github.com/uriparser/uriparser/issues/68#issuecomment-487410836 . Thanks for the report!
