### ISSUE TITLE
Can uriparser also parse IRIs?

### ISSUE THREAD

**Issue by wouterbeek** [uriparser/uriparser#9]
Can uriparser also parse IRIs?  Either way, it may be useful to mentioned this in the `README.md` and/or in the documentation web site.

**Comment by hartwork** [comment]
Hi!

Not without [mapping to a URI](https://tools.ietf.org/html/rfc3987#section-3.1), first, I'm afraid.

I don't really feel like putting `we do RFC 3986, RFC 3987 is not supported` somewhere. It would look sad.

[bbcarchdev/liburi](https://github.com/bbcarchdev/liburi) says to support IRI and relies on uriparser but [I see](https://github.com/bbcarchdev/liburi/issues/7) that you found that one already.

I think I have yet to see an IRI in the wild myself. Out of curiosity, where are you getting IRIs out of or from?

Best, Sebastian

**Comment by hartwork** [comment]
I imagine the amount of changes needed to make uriparser ready for IRI from the inside not too much fun. I'd rather start a new IRI library from scratch. I would need to quit my day job though to have time for that.

**Comment by hartwork** [comment]
If you want to discuss approaches regarding IRI outside of or on top uriparser, I'm happy to take that to phone (see number in whois) or coffee in Berlin. I'll close this ticket now.
